### ISSUE TITLE
Resolve may fail when synchronous_commit is OFF

### ISSUE THREAD

**Issue by luyang177** [pgfdwplus/postgres_fdw_plus#7]
A rare scenario: 
  
suppose three nodes: A, B, C
(1) user connect to node A
(2) set synchronous_commit = OFF on node A
(3) begin a transaction which involve node B and C via FDW
(4) COMMIT it asynchronous on node A, then node A crash
(5) result is: node A lost COMMIT WAL, node B received "COMMIT PREPARED" and committed, node C not received "COMMIT PREPARED"

pgfdw_plus_resolve_foreign_prepared_xacts will fail.

**Comment by MasaoFujii** [comment]
@luyang177 
Yes, this trouble can happen if the node A is configured so that the committed transaction can be lost after the crash recovery, for example, synchronous_commit=off or fsync=off. To prevent this, postgres_fdw_plus assumes certain parameter settings for reliable PostgreSQL server clusters. It may be helpful to document these assumptions for users of postgres_fdw_plus.
